---
title: "Other Work Experience"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<div class=nav>
  <ul>
    <li><a href="index.html">About me</a></li>
    <li><a href="Education.html">Education</a></li>
    <li><a href="Science-and-Technology-Work-Experience.html">Scientific Work Experience</a></li>
    <li><a href="Other-Work-Experience.html">Other Work Experience</a></li>
    <li><a href="Achievements---Publications.html">Achievements and Publications</a></li>
    <li><a href="Skills-and-Interests.html">Skills and Interests</a></li>
  </ul>
</div>

<div class=main>

#### **Bar staff for HAP recruitment** (May 2019 - present)
***
Required resilience, precise money handling and effective communication skills over long shifts.

Essential to be vigilant for underage purchases and inappropriate behaviour.

<br>

#### **University of Glasgow Telephone Campaign** (Jan – March 2018)
***
Raised vital funds to support student scholarships, research, facilities, and equipment for the University as well as establish meaningful relationships with alumni and friends.

<br>

#### **Sales advisor at Stevensons, Oxford** (May - Sept 2017)
***
Assisted customers with school uniform purchasing. This fast-paced environment required quick learning, effective staff coordination and precise till skills. 

<br>

#### **Volunteer at Oxfam Summertown Shop, Oxford** (2012 - 2016)
***
Responsibilities included operating the till, ordering stock and evaluating donations appropriate for selling.

</div>

<div class=footer>
  <hr width="75%" align="center">
    <p>
      <a href="https://www.linkedin.com/in/rifah-abdullah-60b239151/"><b><i>LinkedIn</i></b></a>
      <a href="https://github.com/r-abdullah"><b><i>GitHub</i></b></a>
      <a href="https://orcid.org/0000-0001-8966-2171"><b><i>ORCID</i></b></a>
    </p>
</div>
