---
title: "Skills and Interests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<div class=nav>
  <ul>
    <li><a href="index.html">About me</a></li>
    <li><a href="Education.html">Education</a></li>
    <li><a href="Science-and-Technology-Work-Experience.html">Scientific Work Experience</a></li>
    <li><a href="Other-Work-Experience.html">Other Work Experience</a></li>
    <li><a href="Achievements---Publications.html">Achievements and Publications</a></li>
    <li><a href="Skills-and-Interests.html">Skills and Interests</a></li>
  </ul>
</div>

<div class=main>

#### **IT skills**
***

Proficient in Microsoft Office Suite 

Confident at R  

Capable at SPSS - keen to learn other software such as Matlab and STATA

Learning JavaScript and HTML

<br>

#### **Other skills**
***

Trained PIRGAS rater

Training in laboratory skills such as PCR, Enzyme Digestion and Restriction mapping

<br>

#### **Languages**
***

Native Bengali

Fluent English

GCSE German

<br>

#### **Clubs and Societies**
***

Member of the University’s Psychology Society – often attend additional lectures and seminars to expand my knowledge beyond my course and independent reading.

Member of University’s Badminton Club – play twice a week and have played games for local league tournaments as well as organising tournaments amongst friends.

Peer Assisted Learning Facilitator – assisted and provided support to psychology students in all university years, regarding coursework and other course-related enquiries.

</div>

<div class=footer>
  <hr width="75%" align="center">
    <p>
      <a href="https://www.linkedin.com/in/rifah-abdullah-60b239151/"><b><i>LinkedIn</i></b></a>
      <a href="https://github.com/r-abdullah"><b><i>GitHub</i></b></a>
      <a href="https://orcid.org/0000-0001-8966-2171"><b><i>ORCID</i></b></a>
    </p>
</div>
